### ISSUE TITLE
请问XStuCacheMiddleware这个又不是特性，怎么添加到Action上使用呢？请指教~

### ISSUE THREAD

**Issue by YeLin25789** [imxiongstu/XStu.CacheMiddleware#1]
请问XStuCacheMiddleware这个又不是特性，怎么添加到Action上使用呢？请指教~

**Comment by imxiongstu** [comment]
首先确保Redis是打开状态，然后在管道中，有注册这个中间件，在Action上面添加[Xstu????]的特性，你可以引用命名空间以后，查看，有缓存特性，清理缓存特性，具体ide估计打xstu开头，就会提示出来。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imxiongstu/XStu.CacheMiddleware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月17日(星期五) 下午4:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[imxiongstu/XStu.CacheMiddleware] 请问XStuCacheMiddleware这个又不是特性，怎么添加到Action上使用呢？请指教~ (#1)





 
请问XStuCacheMiddleware这个又不是特性，怎么添加到Action上使用呢？请指教~
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YeLin25789** [comment]
实现了，感谢~
